<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UMQHIUK" failures="1" tests="3" name="ListReportingTest" time="0.609" errors="0" timestamp="2023-10-13T00:52:27 IST">
  <testcase classname="com.prac.ListenerWithExtRep.ListExtRepTestNGClass" name="TestFail" time="0.032">
    <failure type="java.lang.AssertionError" message="expected [9] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [10]
at com.prac.ListenerWithExtRep.ListExtRepTestNGClass.TestFail(ListExtRepTestNGClass.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestFail -->
  <testcase classname="com.prac.ListenerWithExtRep.ListExtRepTestNGClass" name="TestPass" time="0.005"/>
  <testcase classname="com.prac.ListenerWithExtRep.ListExtRepTestNGClass" name="TestSkip" time="0.0">
    <skipped/>
  </testcase> <!-- TestSkip -->
</testsuite> <!-- ListReportingTest -->
